service: wedding-website

provider:
  name: aws
  runtime: nodejs12.x
  stage: main
  region: eu-west-2
functions:
  app:
    handler: "./handler.handler"
    events:
      - http:
          method: ANY
          path: "/"
      - http:
          method: ANY
          path: "{proxy+}"
