service: wedding-website
package:
  exclude:
    - "src/public/images/**"
provider:
  name: aws
  runtime: nodejs12.x
  stage: main
  region: eu-west-2
  apiGateway:
    shouldStartNameWithService: true
functions:
  app:
    handler: "./src/website.handler"
    events:
      - http:
          method: ANY
          path: "/"
      - http:
          method: ANY
          path: "{proxy+}"
plugins:
  - serverless-domain-manager
custom:
  customDomain:
    domainName: "burleywedding.co.uk"
    certificateArn: "arn:aws:acm:eu-west-2:557482387627:certificate/78ed1900-6323-417d-9c3e-0da084c2903a"
    stage: main
    createRoute53Record: true
    autoDomain: true
